function cCombination(b,a,c){this.n=b;this.k=a;this.data=[];if(0>b||0>a)throw"Negative parameter in constructor";if("undefined"!=typeof c&&c.length==a)for(b=0;b<a;b++)this.data.push(c[b]);else for(b=0;b<a;b++)this.data.push(b)}
(function(){cCombination.prototype.n=0;cCombination.prototype.k=0;cCombination.prototype.data=[];cCombination.prototype.isValid=function(){if(this.data.Length!=this.k)return!1;for(var b=0;b<this.k;b++){if(0>this.data[b]||this.data[b]>this.n-1)return!1;for(var a=b+1;a<this.k;a++)if(this.data[b]>=this.data[a])return!1}return!0};cCombination.prototype.successor=function(){if(this.data[0]==this.n-this.k)return null;var b=new cCombination(this.n,this.k),a;for(a=0;a<this.k;a++)b.data[a]=this.data[a];for(a=
this.k-1;0<a&&b.data[a]==this.n-this.k+a;a--);for(b.data[a]++;a<this.k-1;a++)b.data[a+1]=b.data[a]+1;return b};cCombination.numberOfCombinations=function(b,a){if(0>b||0>a)throw"Invalid negative parameter in numberOfCombinations()";if(b<a)return 0;if(b==a||0==a)return 1;var c,d;a<b-a?(c=b-a,d=a):(c=a,d=b-a);for(var e=c+1,f=2;f<=d;f++)e=e*(c+f)/f;return e};cCombination.prototype.element=function(b){lResultData=[];for(var a=0;a<this.k;a++)lResultData.push(0);var c=this.n,d=this.k;b=cCombination.numberOfCombinations(this.n,
this.k)-1-b;for(a=0;a<this.k;a++)lResultData[a]=this.largestValue(c,d,b),b-=cCombination.numberOfCombinations(lResultData[a],d),c=lResultData[a],d-=1;for(a=0;a<this.k;a++)lResultData[a]=this.n-1-lResultData[a];return new cCombination(this.n,this.k,lResultData)};cCombination.prototype.largestValue=function(b,a,c){for(b-=1;cCombination.numberOfCombinations(b,a)>c;)b--;return b};cCombination.prototype.toString=function(){for(var b="{ ",a=0;a<this.k;a++)b+=this.data[a]+" ";return b+"}"};cCombination.unitTest=
function(){var b=new cCombination(52,5),a=cCombination.numberOfCombinations(52,5);if("undefined"!=typeof console)for(console.log("number of combinations = "+a),a=0;10>a;a++)console.log("combination "+a+" = "+b.element(a).toString())}})();
function cCombinationRange(b,a,c){this.n=b;this.kFrom=a;this.kTo=c;this.combinations=[];if(0>b||0>a||0>c)throw"Negative parameter in constructor";if(a>c)throw"invalid arguments";for(;a<=c;a++){for(var d=new cCombination(b,a),e=0;e<a;e++)d.data[e]=e;this.combinations.push(d)}}
(function(){cCombinationRange.prototype.n=0;cCombinationRange.prototype.kFrom=0;cCombinationRange.prototype.kTo=0;cCombinationRange.prototype.combinations=[];cCombinationRange.numberOfCombinations=function(b,a,c){for(var d=0;a<=c;a++)d+=cCombination.numberOfCombinations(b,a);return d};cCombinationRange.prototype.element=function(b){for(var a=null,c,d=this.kFrom;d<=this.kTo;d++){c=cCombination.numberOfCombinations(this.n,d);if(b<c){a=this.combinations[d-this.kFrom].element(b);break}b-=c}return a};
cCombinationRange.unitTest=function(){var b=new cCombinationRange(8,3,5),a=cCombinationRange.numberOfCombinations(8,3,5);if("undefined"!=typeof console)for(console.log("number of combinations = "+a),a=0;100>a;a++)console.log("combination "+a+" = "+b.element(a).toString())}})();
var jChoose={callStack:[],callStackIndex:0,choose:function(b,a,c,d){var e={},f="undefined"!=typeof b?0<=b?b:0:0,g="undefined"!=typeof a?a>=f?a:f:f;a=0;"jQuery"==c?a=d.length:"array"==c&&(a=d.length);jChoose.callStackIndex>jChoose.callStack.length-1?(e={atLeast:f,atMost:g,listType:c,elementCount:a,choiceCount:cCombinationRange.numberOfCombinations(a,f,g),choiceIndex:0,validChoice:!0},jChoose.callStack.push(e)):(e=jChoose.callStack[jChoose.callStackIndex],e.elementCount!=a&&(e.choiceCount=cCombinationRange.numberOfCombinations(e.elementCount,
f,g)),e.validChoice=!0);b=[];"jQuery"==c&&(b=$());if(f<=g)if(0<e.choiceCount){if(e.choiceIndex<e.choiceCount)if(lCombinationRange=new cCombinationRange(e.elementCount,f,g),f=lCombinationRange.element(e.choiceIndex))for(g=0;g<f.data.length;g++){var h=f.data[g];if(h<a)"jQuery"==c?b=b.add(d.eq(h)):b.push(d[h]);else{e.validChoice=!1;break}}else e.validChoice=!1}else 0<f&&(e.validChoice=!1);else e.validChoice=!1;jChoose.callStackIndex++;return b},resetCallStack:function(){jChoose.callStack=[];jChoose.callStackIndex=
0},resetCallStackIndexAndValidChoice:function(){for(var b=jChoose.callStackIndex=0,a=jChoose.callStack.length;b<a;b++)jChoose.callStack[b].validChoice=!0},validChoice:function(){for(var b=0,a=jChoose.callStack.length;b<a;b++)if(!jChoose.callStack[b].validChoice)return!1;return!0}};Array.prototype.choose=function(b,a){return jChoose.choose(b,a,"array",this)};Array.prototype.chooseOne=function(){var b=jChoose.choose(1,1,"array",this);return 0<b.length?b[0]:null};
(function(b){b.fn.choose=function(a,b){return jChoose.choose(a,b,"jQuery",this)};b.fn.chooseOne=function(){return jChoose.choose(1,1,"jQuery",this)}})(jQuery);
